"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Validación de variables críticas para Railway
def validate_critical_settings():
    """Valida que las variables críticas estén configuradas antes de continuar."""
    critical_vars = ['SECRET_KEY']
    missing_vars = []

    for var in critical_vars:
        value = config(var, default=None)
        if not value:
            missing_vars.append(var)

    if missing_vars:
        print(f"⚠️  ADVERTENCIA: Variables críticas faltantes: {', '.join(missing_vars)}")
        print("ℹ️  Usando valores por defecto seguros para continuar...")

# Ejecutar validación
validate_critical_settings()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-production-key-change-in-production-2025')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Leer ALLOWED_HOSTS desde la variable de entorno y manejar distintos tipos
_allowed_hosts_raw = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,10.0.2.2,testserver,192.168.1.11,backendparcial2-production.up.railway.app,*.up.railway.app'
)
if isinstance(_allowed_hosts_raw, str):
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]
elif isinstance(_allowed_hosts_raw, (list, tuple)):
    ALLOWED_HOSTS = [str(h) for h in _allowed_hosts_raw]
else:
    # Fallback: convertir a string para evitar errores de atributo
    ALLOWED_HOSTS = [str(_allowed_hosts_raw)]

# En desarrollo, permitir todos los hosts para facilitar pruebas desde emuladores/dispositivos
if DEBUG:
    ALLOWED_HOSTS = ['*']

# Security settings for production - Railway maneja SSL automáticamente
if not DEBUG:
    # NO usar SECURE_SSL_REDIRECT=True en Railway - ellos manejan SSL
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Opcional: HSTS solo si Railway no lo maneja
    # SECURE_HSTS_SECONDS = 31536000  # 1 year
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'api',
    'products',
    'sales',
    'notifications',
    'voice_commands',
    # 'django_extensions' es opcional en desarrollo; lo añadimos condicionalmente abajo
]

# Añadir apps opcionales solo si están instaladas en el entorno
try:
    # Intentar importar para comprobar si el paquete está disponible
    import django_extensions  # type: ignore
except Exception:
    # No instalado en el entorno; seguimos sin él
    pass
else:
    INSTALLED_APPS.append('django_extensions')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe estar lo más arriba posible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware de Auditoría y Bitácora (debe ir después de AuthenticationMiddleware)
    'sales.middleware_audit.SessionTrackingMiddleware',
    'sales.middleware_audit.AuditMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Intentar usar PostgreSQL primero (producción), fallback a SQLite (desarrollo)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Usar PostgreSQL si DATABASE_URL está configurada (producción)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    # Fallback a configuración individual de PostgreSQL
    try:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DB_NAME', default='railway'),
                'USER': config('DB_USER', default='postgres'),
                'PASSWORD': config('DB_PASSWORD', default='cYpvNcrPVGUMNXKVgkVxeJfEkPJHPbFq'),
                'HOST': config('DB_HOST', default='nozomi.proxy.rlwy.net'),
                'PORT': config('DB_PORT', default='40214'),
                'OPTIONS': {
                    'connect_timeout': 10,
                    'sslmode': 'require' if not DEBUG else 'prefer',
                },
                'CONN_MAX_AGE': 60,
            }
        }
        # Verificar que PostgreSQL esté disponible
        import psycopg2
        psycopg2.connect(
            dbname=config('DB_NAME', default='railway'),
            user=config('DB_USER', default='postgres'),
            password=config('DB_PASSWORD', default='cYpvNcrPVGUMNXKVgkVxeJfEkPJHPbFq'),
            host=config('DB_HOST', default='nozomi.proxy.rlwy.net'),
            port=config('DB_PORT', default='40214')
        ).close()
    except (ImportError, Exception) as e:
        # Fallback a SQLite si PostgreSQL no está disponible
        print(f"PostgreSQL no disponible ({e}), usando SQLite como alternativa")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Cache configuration for ML predictions
# Usar LocMemCache por defecto (no requiere Redis)
# Para producción con Redis, descomentar la configuración Redis y comentar LocMemCache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ml-predictions',
        'TIMEOUT': 900,  # 15 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Configuración alternativa con Redis (requiere: pip install django-redis)
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'ml_predictions',
#         'TIMEOUT': 900,  # 15 minutos
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/app/staticfiles'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS
# Para desarrollo, permitimos todos los orígenes para facilitar la conexión desde Flutter.
# En producción, esto debe ser False y CORS_ALLOWED_ORIGINS debe ser configurado correctamente.
CORS_ALLOW_ALL_ORIGINS = True

# En desarrollo permite orígenes específicos, en producción debe ser más restrictivo
cors_allowed_origins_raw = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000',
    cast=str
)
if isinstance(cors_allowed_origins_raw, str):
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_allowed_origins_raw.split(',') if o.strip()]
else:
    # Asegurar que siempre sea una lista de strings; cubrir casos donde la variable de entorno
    # pueda haber sido interpretada como otro tipo (p.ej. bool)
    if isinstance(cors_allowed_origins_raw, (list, tuple)):
        CORS_ALLOWED_ORIGINS = [str(o) for o in cors_allowed_origins_raw]
    else:
        CORS_ALLOWED_ORIGINS = [str(cors_allowed_origins_raw)]

CORS_ALLOW_CREDENTIALS = True

# Permitir todos los métodos y headers para facilitar desarrollo
# En producción, considera restringir estos valores
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuración de CSRF
# Nota: CSRF Middleware está deshabilitado porque usamos Token Authentication
# Pero definimos trusted origins por si se habilita en el futuro
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://10.0.2.2:8000',  # Para emulador Android
]

# En producción, estas deben ser True si habilitas CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Por defecto requiere autenticación
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Paginación por defecto para listas grandes
}

# --- CONFIGURACIÓN DE ENVÍO DE CORREO ---
# En desarrollo usa console, en producción usa SMTP
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='noreply@example.com')

# Para desarrollo también podemos configurar las credenciales si existen
try:
    if DEBUG and config('EMAIL_HOST_USER', default=''):
        EMAIL_HOST = 'smtp.gmail.com'
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = config('EMAIL_HOST_USER')
        EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
except:
    pass

# --- CONFIGURACIÓN DE STRIPE ---
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')

# URL base del frontend (para construir success_url/cancel_url de Stripe por defecto)
# Ejemplo: http://localhost:3000 o https://mi-dominio.com
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default='http://localhost:3000')

# Listas de seguridad para URLs de retorno opcionales en checkout
# Permiten deep links y dominios específicos cuando el cliente móvil necesite override de success_url/cancel_url
# Notas de robustez:
# - Forzamos a string con str() para evitar que Pylance marque .split sobre bool u otros tipos.
# - Luego normalizamos a lista de strings separando por comas y haciendo strip.
# Formato coma-separada: "miapp,miotraapp"
_allowed_deep_link_schemes_raw: str = str(config('ALLOWED_DEEP_LINK_SCHEMES', default=''))
ALLOWED_DEEP_LINK_SCHEMES = [s.strip() for s in _allowed_deep_link_schemes_raw.split(',') if s.strip()]
# Formato coma-separada: "localhost,mi-dominio.com"
_allowed_return_hosts_raw: str = str(config('ALLOWED_CHECKOUT_RETURN_HOSTS', default='localhost'))
ALLOWED_CHECKOUT_RETURN_HOSTS = [h.strip() for h in _allowed_return_hosts_raw.split(',') if h.strip()]

# --- CONFIGURACIÓN DE FIREBASE CLOUD MESSAGING ---
# Ruta al archivo de credenciales de Firebase
# Descarga el archivo desde Firebase Console > Project Settings > Service Accounts
FIREBASE_CREDENTIALS_PATH = config(
    'FIREBASE_CREDENTIALS_PATH',
    default=str(BASE_DIR / 'firebase-credentials.json')
)

# Credenciales de Firebase en formato base64 (alternativa al archivo físico)
# Útil para deployments en la nube como Railway donde no se pueden subir archivos
FIREBASE_CREDENTIALS_BASE64 = config('FIREBASE_CREDENTIALS_BASE64', default=None)

# Configuración pública de Firebase (para frontend)
# Estas se pueden exponer al cliente ya que no son sensibles
FIREBASE_PUBLIC_API_KEY = config('FIREBASE_PUBLIC_API_KEY', default=None)
FIREBASE_AUTH_DOMAIN = config('FIREBASE_AUTH_DOMAIN', default=None)
FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID', default=None)
FIREBASE_STORAGE_BUCKET = config('FIREBASE_STORAGE_BUCKET', default=None)
FIREBASE_MESSAGING_SENDER_ID = config('FIREBASE_MESSAGING_SENDER_ID', default=None)
FIREBASE_APP_ID = config('FIREBASE_APP_ID', default=None)
FIREBASE_VAPID_KEY = config('FIREBASE_VAPID_KEY', default=None)  # Para web push notifications

# --- CONFIGURACIÓN DE GOOGLE CLOUD SPEECH-TO-TEXT ---
# Ruta al archivo de credenciales de Google Cloud
# Descarga el archivo desde Google Cloud Console > IAM & Admin > Service Accounts
GOOGLE_CLOUD_CREDENTIALS_PATH = config(
    'GOOGLE_CLOUD_CREDENTIALS_PATH',
    default=str(BASE_DIR / 'google-cloud-credentials.json')
)