# Generated by Django 5.1.4 on 2025-11-16 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la campaña', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción de la campaña', null=True)),
                ('campaign_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automática'), ('SYSTEM', 'Sistema')], default='MANUAL', max_length=20)),
                ('total_users', models.PositiveIntegerField(default=0, help_text='Total de usuarios objetivo')),
                ('successful_sends', models.PositiveIntegerField(default=0, help_text='Envíos exitosos')),
                ('failed_sends', models.PositiveIntegerField(default=0, help_text='Envíos fallidos')),
                ('is_completed', models.BooleanField(default=False, help_text='Campaña completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña de Notificación',
                'verbose_name_plural': 'Campañas de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaña a la que pertenece esta notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationcampaign'),
        ),
    ]
