# Generated by Django 5.1.4 on 2025-10-28 13:30

from django.db import migrations
from django.core.management import call_command

def generate_initial_data(apps, schema_editor):
    """
    Llama al management command para generar los datos de demostración.
    El script `generate_demo_sales` es idempotente (no duplicará datos
    si ya existen), por lo que es seguro ejecutarlo aquí.
    """
    try:
        print("\n\n---\n🚀  Ejecutando migración de datos: Poblando la base de datos con datos de demostración...\n")
        call_command('generate_demo_sales')
        print("\n✅  Migración de datos completada.\n---\n")
    except Exception as e:
        print(f"\n❌ ERROR durante la migración de datos: {e}")
        # No lanzamos una excepción para no detener el proceso de migración
        # si la generación de datos falla por alguna razón.

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_paymentmethod_order_payment_method'),
        # Dependencias de otras apps para asegurar que sus tablas existan
        ('api', '0002_alter_profile_role'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_data, reverse_code=migrations.RunPython.noop),
    ]