# Generated by Django 5.1.4 on 2025-11-17 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen del producto')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (0=primera)')),
                ('is_main', models.BooleanField(default=False, help_text='Indica si es la imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order', 'created_at'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
