# Generated by Django 5.1.4 on 2025-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL externa de imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del producto'),
        ),
    ]
